pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=Test - push
      - check-success=Test - pull_request
    actions:
      merge:
        method: merge
      delete_head_branch: {}
